apiVersion: v1
kind: Service
metadata:
  name: webapp

spec:
  # This defines which pods are going to be represented by the service
  selector:
    app: webapp
  ports:
    - name: http
      port: 3000
      nodePort: 30080
  type: NodePort
